name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    steps:
    
      - name: Run docker-compose exec
    run: |
      script -q -e -c "docker-compose exec web bash"
      script -q -e -c "docker-compose exec db psql"
      
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq ca-certificates curl gnupg lsb-release wget


      - name: Build
        run: bash run.sh


      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
