name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq ca-certificates curl gnupg lsb-release wget


      - name: Build
        run: |
        bash 1.sh
        bash 2.sh


      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
