name: Build kernel deb packages and docker
on: push

jobs:
  build:
    name: Build kernel docker
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq ca-certificates gnupg lsb-release wget
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: sudo bash builder-docker-images.sh
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
      - name: Docker image tag
        run: docker tag openkylin:latest ${{ secrets.DOCKERHUB_USERNAME }}/openkylin:latest
      - name: Docker image push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/openkylin:latest